name: logx
description: Simple and concise logs for Dart/Flutter built on top of the developer package.
version: 0.2.0
homepage: https://github.com/vaetas/logx

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1

dev_dependencies:
  pedantic: ^1.11.0

flutter:

